window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t815_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec?rec.querySelector('.t815'):null;if(!menu)return;var isFixed=menu.style.position==='fixed'||window.getComputedStyle(menu).position==='fixed';var isRedactorMode=menu.classList.contains('t815_redactor-mode');if(!isRedactorMode){menu.classList.remove('t815__beforeready');if(isFixed&&menu.getAttribute('data-bgopacity-two')){t_onFuncLoad('t_menu__changeBgOpacity',function(){t_menu__changeBgOpacity(recid,'.t815');window.addEventListener('scroll',t_throttle(function(){t_menu__changeBgOpacity(recid,'.t815')},200))})}
if(isFixed&&menu.getAttribute('data-appearoffset')){menu.classList.remove('t815__beforeready');t_onFuncLoad('t_menu__showFixedMenu',function(){t_menu__showFixedMenu(recid,'.t815');window.addEventListener('scroll',t_throttle(function(){t_menu__showFixedMenu(recid,'.t815')},200))})}}
t_onFuncLoad('t_menu__setBGcolor',function(){t_menu__setBGcolor(recid,'.t815');window.addEventListener('resize',t_throttle(function(){t_menu__setBGcolor(recid,'.t815')},200))})}
function t650_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t650_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var wrapper=rec.querySelector('.t650');if(!wrapper)return;var container=rec.querySelector('.t650__container');if(!container)return;var columnsInRow=Number(container.getAttribute('data-columns-in-row'));if(columnsInRow===0||columnsInRow===''){columnsInRow=1}
var allCols=Array.prototype.slice.call(rec.querySelectorAll('.t-card__col'));var rowsArray=[];for(var i=0;i<allCols.length;i+=columnsInRow){rowsArray.push(allCols.slice(i,i+columnsInRow))}
if(window.innerWidth>=960){for(var i=0;i<rowsArray.length;i++){var row=rowsArray[i];var maxHeight=0;var innerCols=[];for(var j=0;j<row.length;j++){innerCols.push(row[j].querySelector('.t650__inner-col'))}
for(var j=0;j<innerCols.length;j++){var col=innerCols[j];var colText=col.querySelector('.t650__text');var colBtn=col.querySelector('.t650__btn-container');var colHeight=colText.offsetHeight+(colBtn?colBtn.offsetHeight:0);if(colHeight>maxHeight)maxHeight=colHeight}
for(var j=0;j<innerCols.length;j++){innerCols[j].style.height=maxHeight+'px'}}}else{var cols=rec.querySelectorAll('.t650__inner-col');for(var i=0;i<cols.length;i++){cols[i].style.height='auto'}}}
function t503_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t569_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t569');if(!container)return;var lines=rec.querySelectorAll('.t569__line');var blocksCount=container.getAttribute('data-blocks-count');var circleCount=4;if(blocksCount!=='4')circleCount=8;for(var i=0;i<lines.length;i++){var line=lines[i];var cirqles=line.querySelector('.t569__cirqle');for(var j=0;j<circleCount;j++){line.insertBefore(cirqles.cloneNode(!0),cirqles.nextSibling)}}
function t569_update(){var col=rec.querySelector('.t569__col');var colWidth=0;var bgImg=rec.querySelector('.t569__bgimg');var bgWidth=0;if(col){var colStyle=getComputedStyle(col,null);var colPaddingLeft=parseInt(colStyle.paddingLeft)||0;var colPaddingRight=parseInt(colStyle.paddingRight)||0;colWidth=col.clientWidth-(colPaddingLeft+colPaddingRight)}
if(bgImg)bgWidth=bgImg.offsetWidth;for(var i=0;i<lines.length;i++){lines[i].style.maxWidth=(colWidth-bgWidth)+'px'}}
if(window.isMobile){if(typeof jQuery!=='undefined'){$(window).on('orientationchange',t_throttle(t569_update))}else{window.addEventListener('orientationchange',t_throttle(t569_update))}}else{window.addEventListener('resize',t_throttle(t569_update))}
if(typeof jQuery!=='undefined'){$(container).on('displayChanged',t_throttle(t569_update))}else{container.addEventListener('displayChanged',t_throttle(t569_update))}
t569_update()}